version: '3.8'

services:
  
  store:
    image: node:18-alpine
    container_name: store
    restart: unless-stopped
    volumes:
      - ./the-store/node_modules:/app/node_modules
      - ./the-store/uploads:/app/uploads
      - ./the-store/dist:/app/dist
      - ./the-store/medusa-config.js:/app/medusa-config.js
      - ./the-store/package.json:/app/package.json
      - ./the-store/index.js:/app/index.js
    working_dir: /app
    environment:
      DATABASE_URL: postgres://root:root-user@database:5432/thesoul
      DATABASE_TYPE: postgres
      STORE_CORS: http://localhost:7001,http://localhost:3001,http://localhost:3000
      NOVAPOSHTA_API_KEY: 19467b3d870a2da13948cfe6aaa6fd54
      # NODE_ENV: prodction
      NPM_CONFIG_PRODUCTION: false
    ports:
      - 9000:9000
    command: node index.js
    networks:
      - thesoul

  storefront:
    image: node:18-alpine
    container_name: storefront
    restart: unless-stopped
    volumes:
      - ./the-storefront/node_modules:/app/node_modules
      - ./the-storefront/.next:/app/.next
      - ./the-storefront/package.json:/app/package.json
      - ./the-storefront/next.config.js:/app/next.config.js
    environment:
      - SITE_NAME=TheSoul
      - NEXT_PUBLIC_MEDUSA_BACKEND_API=http://localhost:9000
      - NEXT_INTERNAL_MEDUSA_BACKEND_API=http://store:9000
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - thesoul
    

  #The postgres database: 
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root-user
      POSTGRES_USER: root
      POSTGRES_DB: thesoul
    ports:
      - "5432:5432"
    networks:
      - thesoul

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: p@p.ua
  #     PGADMIN_DEFAULT_PASSWORD: 12345678
  #     # PGADMIN_DEFAULT_PASSWORD_FILE: 123
  #     PGADMIN_LISTEN_PORT: 5050
  #   ports:
  #     - "5050:5050"
  #   networks:
  #     - thesoul

networks:
  thesoul:
    driver: bridge

volumes:
  postgres-data:
