version: '3.8'

services:
  
  #The postgres database: 
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root-user
      POSTGRES_USER: root
      POSTGRES_DB: thesoul
    ports:
      - "5432:5432"
    networks:
      - thesoul

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: p@p.ua
  #     PGADMIN_DEFAULT_PASSWORD: 12345678
  #     # PGADMIN_DEFAULT_PASSWORD_FILE: 123
  #     PGADMIN_LISTEN_PORT: 5050
  #   ports:
  #     - "5050:5050"
  #   networks:
  #     - thesoul

networks:
  thesoul:
    driver: bridge

volumes:
  postgres-data:
